
class Datos {

    public static String[] provincias() {

        return new String[] { "Madrid", "Sevilla", "Madrid", "Pontevedra", "Madrid", "Barcelona", "Barcelona", "Madrid",
                "Valencia", "Lleida", "Alicante", "Barcelona", "Madrid", "Madrid", "Valencia", "Madrid", "Barcelona",
                "Madrid", "Barcelona", "Toledo", "Barcelona", "Madrid", "Barcelona", "Murcia", "A Coruña", "Murcia",
                "Zaragoza", "Madrid", "Caceres", "Barcelona", "Vizcaya", "Valencia", "Córdoba", "Asturias", "Madrid",
                "Vizcaya", "Melilla", "Madrid", "Badajoz", "Vizcaya", "Barcelona", "Madrid", "Navarra", "Guipúzcoa",
                "Valencia", "Madrid", "Murcia", "Madrid", "Barcelona", "Granada", "Sevilla", "Guadalajara", "Barcelona",
                "Barcelona", "Vizcaya", "Caceres", "Barcelona", "Asturias", "Asturias", "Madrid", "Valencia",
                "Barcelona", "Salamanca", "Valencia", "Valencia", "Malaga", "Guipúzcoa", "Alicante", "Madrid", "Madrid",
                "Las Palmas", "Sevilla", "Barcelona", "Barcelona", "Madrid", "Madrid", "Madrid", "Madrid", "Jaén",
                "Madrid", "Madrid", "Barcelona", "Madrid", "Zaragoza", "Alicante", "Barcelona", "Madrid", "Tarragona",
                "Madrid", "Cantabria", "Alicante", "Malaga", "Madrid", "Valencia", "Vizcaya", "Zaragoza", "Tarragona",
                "Guipúzcoa", "Asturias", "Navarra", "Murcia", "Malaga", "Girona", "Toledo", "Pontevedra", "Barcelona",
                "Madrid", "Madrid", "Navarra", "Madrid", "Castellón", "Madrid", "Barcelona", "Madrid", "Malaga",
                "Barcelona", "Córdoba", "Madrid", "Pontevedra", "Madrid", "Madrid", "Valencia", "Ciudad Real",
                "Segovia", "Barcelona", "Madrid", "Barcelona", "Caceres", "Castellón", "Madrid", "Madrid", "Castellón",
                "Barcelona", "Valencia", "Madrid", "Cadiz", "Zaragoza", "Huelva", "Madrid", "Malaga", "Las Palmas",
                "Barcelona", "Madrid", "Alicante", "Murcia", "Madrid", "Barcelona", "Madrid", "Castellón", "Pontevedra",
                "Barcelona", "Barcelona", "Ciudad Real", "Barcelona", "Pontevedra", "Navarra", "Madrid", "Valladolid",
                "Asturias", "Segovia", "Lleida", "Asturias", "Valencia", "Albacete", "Barcelona", "Barcelona",
                "Valencia", "Madrid", "Madrid", "Valladolid", "Tarragona", "Barcelona", "Madrid", "Granada",
                "Valladolid", "Asturias", "Albacete", "Barcelona", "Barcelona", "Guipúzcoa", "Alicante", "Barcelona",
                "Madrid", "Córdoba", "Madrid", "Lugo", "Cadiz", "Barcelona", "Cadiz", "Valencia", "Alicante", "Madrid",
                "Malaga", "Alicante", "Madrid", "Madrid", "Cadiz", "Barcelona", "Barcelona", "Sevilla", "Barcelona",
                "Valladolid", "Alicante", "Madrid", "Badajoz", "Castellón", "Murcia", "Zaragoza", "Barcelona",
                "Barcelona", "Valladolid", "Tarragona", "Barcelona", "Barcelona", "Zaragoza", "Madrid", "Barcelona",
                "Pontevedra", "Madrid", "Guadalajara", "Barcelona", "Alicante", "Madrid", "Zaragoza", "Navarra",
                "Barcelona", "Barcelona", "Alicante", "Barcelona", "León", "Madrid", "Guadalajara", "Madrid",
                "Valencia", "Las Palmas", "Madrid", "Barcelona", "Zaragoza", "Pontevedra", "Barcelona", "Madrid",
                "Madrid", "Barcelona", "Vizcaya", "Malaga", "Almería", "Madrid", "Guipúzcoa", "Valencia", "Barcelona",
                "Madrid", "Lleida", "Navarra", "Sevilla", "Barcelona", "Madrid", "Barcelona", "A Coruña", "Madrid",
                "Madrid", "Granada", "Barcelona", "Barcelona", "Barcelona", "Cantabria", "Alicante", "Barcelona",
                "Barcelona", "Madrid", "Madrid", "Valencia", "Navarra", "Girona", "Cantabria", "Caceres", "Guipúzcoa",
                "Barcelona", "Madrid", "Murcia", "Madrid", "Barcelona", "Vizcaya", "Navarra", "Barcelona", "Zaragoza",
                "Guipúzcoa", "Sevilla", "Pontevedra", "Granada", "Cantabria", "Sevilla", "Granada", "Caceres",
                "Tarragona", "Barcelona", "Valencia", "Madrid", "Alicante", "Alicante", "Madrid", "Madrid", "Madrid",
                "Barcelona", "Madrid", "Granada", "Murcia", "Guipúzcoa", "Malaga", "Barcelona", "Navarra", "Madrid",
                "Barcelona", "Navarra", "Murcia", "Madrid", "Valladolid", "Barcelona", "Guipúzcoa", "Barcelona",
                "Madrid", "Barcelona", "Guipúzcoa", "Navarra", "Valencia", "Castellón", "Barcelona", "Granada",
                "Valencia", "Madrid", "Girona", "Barcelona", "León", "Madrid", "Barcelona", "Madrid", "Cadiz",
                "Zaragoza", "Madrid", "Barcelona", "Madrid", "Albacete", "Madrid", "Castellón", "Madrid", "Barcelona",
                "Madrid", "Malaga", "Madrid", "Barcelona", "Madrid", "Madrid", "Madrid", "Barcelona", "Madrid",
                "Madrid", "Valladolid", "Madrid", "Madrid", "Madrid", "Valladolid", "Valladolid", "Caceres",
                "Barcelona", "Valencia", "Madrid", "Tarragona", "Huelva", "Valencia", "Barcelona", "Barcelona",
                "Madrid", "Valencia", "Malaga", "Barcelona", "Girona", "Barcelona", "Barcelona", "Murcia", "Murcia",
                "Alicante", "Madrid", "Valencia", "Zaragoza", "Zaragoza", "Pontevedra", "Barcelona", "Salamanca",
                "Zaragoza", "Barcelona", "Madrid", "Avila", "Toledo", "Valencia", "Barcelona", "Malaga", "Barcelona",
                "Madrid", "Malaga", "Madrid", "Alicante", "Madrid", "Barcelona", "Malaga", "Vizcaya", "Madrid",
                "Valencia", "Madrid", "Barcelona", "Toledo", "Barcelona", "Madrid", "Badajoz", "Madrid", "Madrid",
                "Guipúzcoa", "Barcelona", "Cantabria", "Caceres", "Barcelona", "Barcelona", "Guadalajara", "Barcelona",
                "Barcelona", "Zaragoza", "Pontevedra", "Valencia", "Córdoba", "Caceres", "Vizcaya", "Madrid",
                "Barcelona", "Madrid", "Sta. C. Tenerife", "Cantabria", "Barcelona", "Madrid", "Navarra", "Tarragona",
                "Sevilla", "Madrid", "Lleida", "Sevilla", "Alicante", "Madrid", "Madrid", "Malaga", "Guipúzcoa",
                "Barcelona", "Tarragona", "Navarra", "Valencia", "Madrid", "Barcelona", "Toledo", "Malaga", "Barcelona",
                "Malaga", "Madrid", "Valencia", "Almería", "Navarra", "Vizcaya", "Barcelona", "Barcelona", "Tarragona",
                "Girona", "Córdoba", "Madrid", "Madrid", "Sevilla", "León", "Cadiz", "Sevilla", "Huelva", "Barcelona",
                "Cadiz", "Madrid", "Valencia", "Sevilla", "Barcelona", "Barcelona", "Barcelona", "Valencia", "Madrid",
                "Sevilla", "Barcelona", "Murcia", "Madrid", "Alicante", "Madrid", "A_Coruna", "Barcelona", "Madrid",
                "Barcelona", "Madrid", "Alicante", "Malaga", "Barcelona", "Jaén", "Jaén", "Madrid", "Murcia",
                "Sta. C. Tenerife", "Navarra", "Madrid", "Zaragoza", "Tarragona", "Vizcaya", "Barcelona", "Vizcaya",
                "Malaga", "Valencia", "Cantabria", "Valencia", "Valladolid", "Barcelona", "Barcelona", "Tarragona",
                "Lleida", "Barcelona", "Vizcaya", "Pontevedra", "Zaragoza", "Valencia", "Madrid", "Alicante", "Madrid",
                "Madrid", "Alicante", "Guipúzcoa", "Malaga", "Guipúzcoa", "Madrid", "Madrid", "Girona", "Barcelona",
                "Madrid", "Murcia", "Madrid", "Pontevedra", "Madrid", "Barcelona", "Madrid", "Guadalajara",
                "Guadalajara", "Madrid", "Madrid", "Madrid", "Valencia" };

    } // metodo provincias

} // clase Spain